name: Build and Push
on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%s')" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2      
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: europe-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCLOUD_ARTIFACT_REGISTRY_KEY }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            europe-docker.pkg.dev/rpcfast/rpcfast-mempool/gateway
          tags: |
            type=ref,enable=true,priority=600,prefix=,suffix=-${{ steps.date.outputs.date }},event=branch
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}